create table suprimento (id int not null,
						 id_ativo char default 'N' not null,
						 vl_max_diario decimal(14,2) null,
						 vl_max_operacao decimal(14,2) null,
						 id_exibe_inventario char default 'N' not null,
						 id_balanceamento_cedulas char default 'N' not null,
						 cd_usuario_alt varchar(10) not null,
						 dt_inclusao datetime not null,
						 dt_alteracao datetime not null,
						 primary key (id));

create table saque (id int not null,
					id_ativo char default 'N' not null,
					vl_max_diario decimal(14,2) null,
					vl_max_operacao decimal(14,2) null,
					id_exibe_inventario char default 'N' not null,
					id_balanceamento_cedulas char default 'N' not null,
					cd_usuario_alt varchar(10) not null,
					dt_inclusao datetime not null,
					dt_alteracao datetime not null,
					primary key (id));

create table deposito (id int not null,
					   id_ativo char default 'N' not null,
					   vl_max_diario decimal(14,2) null,
					   vl_max_operacao decimal(14,2) null,
					   cd_usuario_alt varchar(10) not null,
					   dt_inclusao datetime not null,
					   dt_alteracao datetime not null,
					   primary key (id));

create table retirada (id int not null,
					   id_ativo char default 'N' not null,
					   vl_max_diario decimal(14,2) null,
					   vl_max_operacao decimal(14,2) null,
					   cd_usuario_alt varchar(10) not null,
					   dt_inclusao datetime not null,
					   dt_alteracao datetime not null,
					   primary key (id));

create table tcr (id int not null,
				  ds_nome varchar(100) not null,
				  cd_posto int not null,
				  cd_coop int not null,
				  id_tesoureiro_ativo char default 'N' not null ,
				  cd_usuario_alt varchar(10) not null,
				  dt_inclusao datetime not null,
				  dt_alteracao datetime not null,
				  id_limite_excedido_autoriza_tesoureiro char default 'N' not null,
				  id_suprimento int null,
				  id_retirada int null,
				  id_saque int null,
				  id_deposito int null,
				  primary key (id),
				  foreign key (id_suprimento) references suprimento(id),
				  foreign key (id_retirada) references retirada(id),
				  foreign key (id_saque) references saque(id),
				  foreign key (id_deposito) references deposito(id));